CREATE DATABASE LIVRARIA;

USE LIVRARIA;

CREATE TABLE LIVROS(
	NOME VARCHAR(100),
	AUTOR VARCHAR(50),
	SEXO CHAR(1),
	PAGINAS INT(5),
	EDITORA VARCHAR(30),
	VALOR FLOAT(8,2),
	ESTADO_DA_EDITORA CHAR(2),
	ANO_DE_PUBLICACAO INT (4)
);	

INSERT INTO LIVROS(NOME, AUTOR, SEXO, PAGINAS, EDITORA, VALOR, ESTADO_DA_EDITORA, ANO_DE_PUBLICACAO) VALUES ('Cavaleiro Real','Ana Claudia','F',465,'Atlas',49.90,'RJ',2009);
INSERT INTO LIVROS(NOME, AUTOR, SEXO, PAGINAS, EDITORA, VALOR, ESTADO_DA_EDITORA, ANO_DE_PUBLICACAO) VALUES ('SQL para leigos','João Nunes','M',450,'Addison',98.00,'SP',2018);
INSERT INTO LIVROS(NOME, AUTOR, SEXO, PAGINAS, EDITORA, VALOR, ESTADO_DA_EDITORA, ANO_DE_PUBLICACAO) VALUES ('Receitas Caseiras','Celia Tavares','F',210,'Atlas',45,'RJ',2008);
INSERT INTO LIVROS(NOME, AUTOR, SEXO, PAGINAS, EDITORA, VALOR, ESTADO_DA_EDITORA, ANO_DE_PUBLICACAO) VALUES ('pESSOAS eFETIVAS', 'Eduardo Santos', 'M', 390 , 'Beta', 45.00, 'RJ', 2008);
INSERT INTO LIVROS(NOME, AUTOR, SEXO, PAGINAS, EDITORA, VALOR, ESTADO_DA_EDITORA, ANO_DE_PUBLICACAO) VALUES ('Habitos Saudáveis', 'Eduardo Santos',	'M', 630, 'Beta', 150.98, 'RJ', 2019);
INSERT INTO LIVROS(NOME, AUTOR, SEXO, PAGINAS, EDITORA, VALOR, ESTADO_DA_EDITORA, ANO_DE_PUBLICACAO) VALUES ('A Casa Marrom', 'Hermes Macedo', 'M', 250, 'Bubba', 60, 'MG', 2016);
INSERT INTO LIVROS(NOME, AUTOR, SEXO, PAGINAS, EDITORA, VALOR, ESTADO_DA_EDITORA, ANO_DE_PUBLICACAO) VALUES ('Estacio Querido',	'Geraldo Francisco', 'M', 310, 'Insignia', 100.00, 'ES', 2015);
INSERT INTO LIVROS(NOME, AUTOR, SEXO, PAGINAS, EDITORA, VALOR, ESTADO_DA_EDITORA, ANO_DE_PUBLICACAO) VALUES ('Pra sempre amigas', 'Leda Silva',	'F', 510, 'Insignia', 78.98, 'ES',2011);
INSERT INTO LIVROS(NOME, AUTOR, SEXO, PAGINAS, EDITORA, VALOR, ESTADO_DA_EDITORA, ANO_DE_PUBLICACAO) VALUES ('Copas Inesqueciveis',	'Marco Alcantara', 'M', 200, 'Larson', 130.98, 'RS', 2018);
INSERT INTO LIVROS(NOME, AUTOR, SEXO, PAGINAS, EDITORA, VALOR, ESTADO_DA_EDITORA, ANO_DE_PUBLICACAO) VALUES ('O poder da mente', 'Clara Mafra',	'F',	120, 'Continental',	56.58, 'SP', 2017);

/*1 – Trazer todos os dados*/

SELECT * FROM LIVROS ;
SELECT NOME, AUTOR, SEXO, PAGINAS, EDITORA, VALOR, ESTADO_DA_EDITORA, ANO_DE_PUBLICACAO FROM livros;
/**/
/*2 – Trazer o nome do livro e o nome da editora*/

SELECT NOME, EDITORA FROM livros;

/*3 – Trazer o nome do livro e a UF dos livros publicados por autores do sexo masculino.*/

SELECT NOME, ESTADO_DA_EDITORA FROM livros
WHERE SEXO = 'M';

/*4 - Trazer o nome do livro e o número de páginas dos livros publicados por autores do sexo feminino.*/

SELECT NOME, PAGINAS FROM livros
WHERE SEXO = 'F';

/*5 – Trazer os valores dos livros das editoras de São Paulo.*/

SELECT VALOR FROM livros
WHERE ESTADO_DA_EDITORA = 'SP';

/*6 – Trazer os dados dos autores do sexo masculino que tiveram livros publicados por São Paulo ou Rio de Janeiro (Questão Desafio)*/

SELECT AUTOR, SEXO, ESTADO_DA_EDITORA FROM livros
WHERE SEXO = 'M'
AND (ESTADO_DA_EDITORA = 'SP' 
OR ESTADO_DA_EDITORA = 'RJ');
