#Modelagem Básica - ENTIDADE = TABELA

#CLIENTE
#TIPAGEM
#NOME - CARACTERE(30)
#CPF - NUMERICO(11)
#EMAIL - CARACTERE(30)
#TELEFONE - CARACTERE(30)
#ENDERECO - CARACTERE(30)
#SEXO - CARACTERE(1)

#PROCESSOS DE MODELAGEM 

#FASE 1 E FASE 2 - AD ADM DE DADOS
MODELAGEM CONCEITUAL - RASCUNHO
MODELAGEM LÓGICA - BR-Modelo | Star-UML | MySQL Workbench | Qualquer programa de Modelagem

#FASE 3 DBA / AD

MODELAGEM FÍSICA - Scripts de banco

#===============================================================================================

#INICIANDO A MODELAGEM FÍSICA 
#CIANDO O BANCXO DE DADOS 

CREATE DATABASE PROJETO; # PROJETO NOME DO BANCO

# CONECTANDO-SE AO BANCO

USE PROJETO;

#CRIANCO A TABELA DE CLIENTES

CREATE TABLE CLIENTE(
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR (30),
	CPF INT(11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR (100)
);

#VERIFICANDO AS TABELAS DO BANCO

SHOW TABLES;

#DESCOBRINCO COM É A ESTRUTURA DE UMA TABELA 

DESC CLIENTE;

#Inserindo dados e valores nulos

use projeto;

#Mostrando as tabelas
 show tables;

#exibindo a estrutura de uma tabela
desc cliente;

#sintaxe basica de inserção - INSERT INTO TABELA

#FORMA 01 - OMITINDO AS COLUNAS

INSERT INTO CLIENTE VALUES('JOAO','M','JOAO@GMAIL.COM',988638273,'22923110','MAIA LACERDA - ESTACIO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES('CELIA','F','CELIA@GMAIL.COM',541521456,'25078869','RIACHUELO - CENTRO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES('JORGE','M',NULL,885755896,'58748895','OSCAR CURY - BOM RETIRO - PATOS DE MINAS - MG');

#Melhor forma para inserção de dados
#FORMA 02 - COLOCANDO AS COLUNAS

INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('LILIAN','F','SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ','947785696',887774856);

FORMA 03 - INSERT COMPACTO - SOMENTE MYSQL
#Funciona apenas no MySQL
INSERT INTO CLIENTE VALUES('ANA','F','ANA@GLOBO.COM',85548962,'548556985','PRES ANTONIO CARLOS - CENTRO - SAO PAULO - SP'),
                          ('CARLA','F','CARLA@TERATI.COM.BR',7745828,'66587458','SAMUEL SILVA - CENTRO - BELO HORIZONTE - MG');
						  
INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('CLARA','F','SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ','883665843',99999999999); #CPF ultrapassa o range recomenda-se usar char ou varchar

INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('CLARA','F','SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ','883665843',22222222222); #CPF ultrapassa o range recomenda-se usar char ou varchar