#Modelagem Básica - ENTIDADE = TABELA

#CLIENTE
#TIPAGEM
#NOME - CARACTERE(30)
#CPF - NUMERICO(11)
#EMAIL - CARACTERE(30)
#TELEFONE - CARACTERE(30)
#ENDERECO - CARACTERE(30)
#SEXO - CARACTERE(1)

#PROCESSOS DE MODELAGEM 

#FASE 1 E FASE 2 - AD ADM DE DADOS
MODELAGEM CONCEITUAL - RASCUNHO
MODELAGEM LÓGICA - BR-Modelo | Star-UML | MySQL Workbench | Qualquer programa de Modelagem

#FASE 3 DBA / AD

MODELAGEM FÍSICA - Scripts de banco

#===============================================================================================

#INICIANDO A MODELAGEM FÍSICA 
#CIANDO O BANCXO DE DADOS 

CREATE DATABASE PROJETO; # PROJETO NOME DO BANCO

# CONECTANDO-SE AO BANCO

USE PROJETO;

#CRIANCO A TABELA DE CLIENTES

CREATE TABLE CLIENTE(
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR (30),
	CPF INT(11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR (100)
);

#VERIFICANDO AS TABELAS DO BANCO

SHOW TABLES;

#DESCOBRINCO COM É A ESTRUTURA DE UMA TABELA 

DESC CLIENTE;

#Inserindo dados e valores nulos

use projeto;

#Mostrando as tabelas
 show tables;

#exibindo a estrutura de uma tabela
desc cliente;

#sintaxe basica de inserção - INSERT INTO TABELA

#FORMA 01 - OMITINDO AS COLUNAS // Deve ser na exata que estiver na tabela

INSERT INTO CLIENTE VALUES('JOAO','M','JOAO@GMAIL.COM',988638273,'22923110','MAIA LACERDA - ESTACIO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES('CELIA','F','CELIA@GMAIL.COM',541521456,'25078869','RIACHUELO - CENTRO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES('JORGE','M',NULL,885755896,'58748895','OSCAR CURY - BOM RETIRO - PATOS DE MINAS - MG'); //Caso não preencher o campo email com NULL, o sistema vai entender que o telefone é o email e vai dar ero dai pra frente em formato "Cascata"

#Melhor forma para inserção de dados
#FORMA 02 - COLOCANDO AS COLUNAS

INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('LILIAN','F','SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ','947785696',887774856);

FORMA 03 - INSERT COMPACTO - SOMENTE MYSQL
#Funciona apenas no MySQL
INSERT INTO CLIENTE VALUES('ANA','F','ANA@GLOBO.COM',85548962,'548556985','PRES ANTONIO CARLOS - CENTRO - SAO PAULO - SP'),
                          ('CARLA','F','CARLA@TERATI.COM.BR',7745828,'66587458','SAMUEL SILVA - CENTRO - BELO HORIZONTE - MG');
						  
INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('CLARA','F','SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ','883665843',99999999999); #CPF ultrapassa o range recomenda-se usar char ou varchar

INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('CLARA','F','SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ','883665843',22222222222); #CPF ultrapassa o range recomenda-se usar char ou varchar

# O COMANDO SELECT - Seleção ptojeção e Junção "SELECT faz parte da projeção"

SELECT NOW() as DATA_HORA;
SELECT NOW() as DATA_HORA, 'EMERSON OLIVEIRA' AS ALUNO;

SELECT 'EMERSON OLIVEIRA';
SELECT 'BANCO DE DADOS';

#ALIAS DE COLUNAS

SELECT NOME, SEXO, EMAIL FROM CLIENTE; /*Retorna NOME, SEXO, e EMAIL DA TABELA CLIENTE */
SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE; /*Retorna NOME, SEXO, e EMAIL DA TABELA CLIENTE PORÉM MUDA O NOME DA COLUNA "NOME PARA CLIENTE*/
SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE; /*RETORNA  NOME, SEXO, EMAIL E ENDERECO DA TABLE CLIENTE*/
SELECT NOME, SEXO, EMAIL, ENDERECO, NOW() AS DATA_HORA FROM CLIENTE; /*RETORNA  NOME, SEXO, EMAIL E ENDERECO DA TABLE CLIENTE DATA E HORA QUE A QUERY FOI FEITA*/

/* RECOMENDADO NÃO DIGITAR DIRETAMENTE NO TERMINAL "BANCO" 
 CREATE TABLE CLIENTE(
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR (30),
	CPF INT(11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR (100)
);
*/

#Com a projeção é possivel manipular a visualização dos dados da maneira que for melhor 
/*EX:
SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE; /*RETORNA  NOME, SEXO, EMAIL E ENDERECO DA TABLE CLIENTE
SELECT SEXO, NOME, ENDERECO, EMAIL FROM CLIENTE; /*RETORNA  SEXO, NOME, ENDERECO E EMAIL DA TABLE CLIENTE
*/

SELECT * FROM CLIENTE; /* APENAS PARA USO ACADEMICO Retorna todos os dados da tabela */

#FILTROS

/* Não filtra a nivel de colunas e sim a nivel de linhas */

SELECT NOME, SEXO FROM CLIENTE /*RETORNA TODOS OS NOMES QUE SEJAM DO SEXO MASCULINO "M" NA TABELA CLIENTE */
WHERE SEXO = 'M';

SELECT NOME, ENDERECO FROM CLIENTE /*RETORNA OS NOMES DE ENDEREÇOS QUE SEJAM DO SEXO FEMININO*/
WHERE SEXO = 'F';

SELECT NOME, SEXO FROM CLIENTE /*Empty set (0.00 sec) = Set de dados Vazio*/
WHERE ENDERECO = 'RJ';

/*UTILIZANDO O LIKE*/

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE 'RJ';

/* CARACTER CORINGA % => QUALQUER COISA */

SELECT NOME, SEXO FROM CLIENTE /* '%RJ' RETORNA TODOS OS DADOS QUE COMEÇA COM QUALQUER COISA "DADO" E TERMINA COM RJ */
WHERE ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE /* 'ERNESTO MELONO%' RETORNA TODOS OS DADOS QUE COMEÇA COM ERNESTO MELONI E TERMINA COM COISA "DADO" E TERMINA COM RJ */
WHERE ENDERECO LIKE 'ERNESTO MELONI%';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE /*%CENTRO% RETORNA DADOS QUE COMEÇA COM QUALQUER COISA NO MEIO TEM CENTRO TERMINA COM QUALQUER COISA*/
WHERE ENDERECO LIKE '%CENTRO%';









